# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:        13

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: "$2y$13$gjjUJGdWpujJlnulSnw1Qe/1oRHRA3/NLVLVslkFd27jm3Jj2jop."
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        admin_secured_area:
            pattern: ^/admin/
            http_basic:
                realm: "Secured Admin Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
